### PR TITLE
Fixed suggestions made by TSE

### PR DESCRIPTION
**Pull request by marcoshdezcam**
We have fixed the problem with the table image.

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team!
Your work is looking exquisite :ok_hand: Please consider the following comments, make the necessary changes and submit for another review

#### Links
Please consider every item that is a link in the original site and make corresponding items in your project links. One such item is the images in the "More in space and cosmos section".

#### Fixed footer
Please note that as per requirements, both your header and footer are to be fixed to the top and bottom of the page respectively.

#### Table image
Please note that your table image still has some text(on the bottom row) encroaching into the image, consider making adjustments to this.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by mosesogwo** [comment]
### Hi @Emmanuelaaron, @marcoshdezcam. Good job:+1:. But I can't approve this yet for these reasons:

1. You haven't setup stickler for this project. Sorry that this wasn't pointed out earlier.

2. The title of your README is **HTML Forms.**.

Kindly fix these and submit another code review request.

**Good luck:stars:**

### Status: Changes required.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### Hi @Emmanuelaaron, @marcoshdezcam. Good job:+1:. But I can't approve this yet for these reasons:

1. You haven't setup stickler for this project. Sorry that this wasn't pointed out earlier.

2. The title of your README is HTML Forms..

Kindly fix these and submit another code review request.

**Good luck:stars:**
Status: Changes required.

**Review by mosesogwo — CHANGES_REQUESTED** [review]
### :clap:Stickler is still not properly setup. The filename is .stickler.yml, not stickler.yml and the content is also different from what you have. Also remember to enable stickler for this repository so that the checks can run.

See full instructions here https://github.com/microverseinc/linters-config/tree/master/css

**Review by mosesogwo — APPROVED** [review]
**Great! :trophy:Congratulations. You can now merge to master.**

Please remove the old stickler.yml file from your project folder before you merge.

**Good luck in your next project:stars:**

### Status: Approved!

**Pull request merged**
